### ISSUE TITLE
NextJS web worker?

### ISSUE THREAD

**Issue by dimasandriano** [shkreios/vite-react-pdf-renderer-web-worker#1]
can i use web worker in nextjs for render pdf with react pdf renderer? I have tried something like this repository but it failed because it uses nextjs.

**Comment by shkreios** [comment]
@dimasandriano i am using this in a similar way with nextjs on another project. What is bug you are running into?

**Comment by dimasandriano** [comment]
@shkreios I don't know, maybe I'm not smart enough to try it in nextjs. can i ask for an example of its use in nextjs please?

**Comment by shkreios** [comment]
@dimasandriano here you go https://stackblitz.com/github/shkreios/nextjs-pdf-renderer-web-worker, keep in mind this may not be the best way to do this for your usecase. 

The code is mostly identical, the only thing that was vite specific is the import a worker using [query-suffix](https://v3.vitejs.dev/guide/features.html#import-with-query-suffixes) like so [`import Worker from './workers/pdf.worker?worker'`](https://github.com/shkreios/vite-react-pdf-renderer-web-worker/blob/main/src/useRenderPDF.ts#L7)

**Comment by dimasandriano** [comment]
thank u sir
